name = "EnergyModelsCompliance"
uuid = "a12c78df-351d-47be-9a81-17a33aab13b1"
authors = ["Julian Straus <Julian.Straus@sintef.no>"]
version = "0.1.0"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
EnergyModelsGeography = "3f775d88-a4da-46c4-a2cc-aa9f16db6708"

[extensions]
EMGExt = "EnergyModelsGeography"

[compat]
EnergyModelsBase = "0.9.0"
EnergyModelsGeography = "0.11.0"
HiGHS = "1.15.0"
JuMP = "1.24.0"
Test = "1.10.0"
TimeStruct = "0.9.2"
Julia = "1.10"
